[[processes]]
  name = "web"
  start = "npm run start:prod"

[build.npm]
  # Explicitly install with production dependencies only to reduce image size
  installCmd = "npm ci --only-production"

[phases]
  build = [
    "npm install",
    "npm run build"
  ]