[[processes]]
  name = "web"
  start = "npm run start:prod"

[build.npm]
  installCmd = "npm ci --only=production --verbose"

[phases]
  build = [
    "npm ci --only=production --verbose",
    "npm run build"
  ]