```typescript
export enum NotificationEvent {
  MATCHING_RESULTS = 'MATCHING_RESULTS',
  RESERVATION_INFORMATION = 'RESERVATION_INFORMATION',
  RESERVATION_CANCELLATION = 'RESERVATION_CANCELLATION',
}
```